services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=baalbade
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=piscineds
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # Add healthcheck to ensure database is ready
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U baalbade -d piscineds"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
